### ISSUE TITLE
MQTT push messages doesn't work after HA june upgrade

### ISSUE THREAD

**Issue by bartalz** [dylangmiles/docker-must-homeassistant#7]
I'm using MQTT push messages from HA to optimize my inverter states. However from HA June update the push messages from HA stopped working, and also all my automation connected to it. Like: Publish on mqtt topic from HA -> homeassistant/sensor/must-inverter -a 20109 -v 3. This is now not changing the value of 20109 to 3. In MQTT explorer I see the value in the same way like before, however no change on inverter. If I'm using command at docker: dotnet inverter.dll set -a 20109 -v 3 this is working fine. Can you give me any hint to fix this? Thank you!

**Comment by dylangmiles** [comment]
After updating HA recently I am also having the same problem. It is like the message is not going out from HA. If I look at the Docker logs for this app I don't see the messages being received. Maybe it has to do with the MQTT topic but not sure at this point.

I will take a look at let you know if I find a solution.

**Comment by dylangmiles** [comment]
It looks like after upgrade the username and password for the MQTT broker were changed in HA. So I got the new username and password in HA | Settings | Devices and Services | Integrations | MQTT | Mosquitto Broker | Configure and then applied them in the app configuration file: src/inverter/mqtt.json

Because of the username and password change the app was not able to subscribe to the 'homeassistant/sensor/must-inverter' topic where I publish my switch commands from HA.

I am including my config from configuration.yml for the switch as the format of this has changed slightly with newer versions of the MQTT HA plugin:

```
mqtt:  
    - switch:
        unique_id: switch.must_inverter
        name: "Inverter Switch"
        state_topic: "homeassistant/sensor/must-inverter"
        command_topic: "homeassistant/sensor/must-inverter"
        payload_on: "-a 20109 -v 4"
        payload_off: "-a 20109 -v 3"
        state_on: "-a 20109 -v 4"
        state_off: "-a 20109 -v 3"
        optimistic: false
        qos: 0
        retain: true
```
